- name: source files for aptitude
  hosts:
    - staging
    - demo
    - myclimate
  user: root
  tasks:
    - action: template src=../etc/apt/sources.list dest=/etc/apt/sources.list
    - action: file dest=/etc/apt/sources.list.d mode=755 owner=root group=root state=directory
    - action: template src=../etc/apt/sources.list.d/puppet.list dest=/etc/apt/sources.list.d/puppet.list
